### ISSUE TITLE
title of fields must be without spaces

### ISSUE THREAD

**Issue by jeblister** [kevzettler/gatsby-source-airtable#2]
I test this plugin with a airtable base and i noticed that to not have `null` returned from a field on airtable when Querying with graphql the title of fields must without spaces like (DevCost or Dev_Cost).
Is there a possible update to bypass this limitation ?

**Comment by kevzettler** [comment]
Can you provide a further example?

Like an example Table with field names and corresponding graphQL query?

I imagine some preprocessing would have to be done on the fields names at: 

https://github.com/kevzettler/gatsby-source-airtable/blob/master/src/gatsby-node.js#L40

Does that sound correct?

**Comment by edbrannin** [comment]
GraphQL:
```
  query MensGroups {
    allAirtableMensGroups {
      edges {
        node {
          Group_Name
          Contact_Name
          Contact_Phone
          Contact_Email
          Parish
          Town
          Website
          Address
        }
      }
    }
  }
```

Table: Same columns above, except columns have spaces instead of underscores -- `Group Name`, etc.

Gatsby's GraphQL magic does the space-to-underscore conversion for type inference (the above field names were autocompleted in the built-in Graphiql UI) but doesn't seem to do the same for nodes.  I wonder if this is best fixed there.

**Comment by edbrannin** [comment]
I've minimally reproduced this issue with just Gatsby.  See the above-linked issue for further developments.

**Comment by kevzettler** [comment]
@edbrannin great investigative work

**Comment by jbolda** [comment]
This is fixed in `latest`. Feel free to open an issue if it persists.
