### ISSUE TITLE
configuration - How can we have data from multiple tables

### ISSUE THREAD

**Issue by jeblister** [kevzettler/gatsby-source-airtable#3]
One of the biggest benefits of GraphQL is how it allows you traverse hierarhical data in a single query. 

That will be awesome if we can query data from multiple tables.

For example, if i need a user with his first 10 posts the following graphql query accomplishes this task:

```
query GetUserAndPosts {
  getUser(id: 1) {
    id
    name
    posts(first: 10) {
      id
      title
      content
    }
  }
}
```

**Comment by kevzettler** [comment]
This is a complicated request because of the relationship between GraphQL and the AirtableAPI.

 following: https://community.airtable.com/t/api-idea-graphql-endpoint/3639
If Airtable themselves had a GraphQL endpoint this would be a trivial feature to proxy the gatsby GraphQL to Airtable.

I might be wrong about this and haven't thought too deeply about it but, here's what I think would have to be implemented to get the desired behavior.

* Query the Airtable "base" for available table names 
  I don't think there currently is even an Airtable endpoint to get a list of table names

* Create Gatsby "nodes" for each of the tables their fields
  I'm not how to create nested Gatsby nodes here.

* ???
 I will have to look at this more and get a better picture of the effort. 

I appreciate any other thoughts and discussion here.

**Comment by edbrannin** [comment]
For the first point: suppose we make that part of the configuration a mapping from GraphQL name to table name?

Until there's a way to query for a list of tables, just having a way to list more than one table to query would be a win.

**Comment by edbrannin** [comment]
Second point: what about making the Table a node and its rows a nested set of objects?

Something like:
```
  tables.forEach(({ tableName, queryName }) => {
    const rows = await dumpTable(tableName)
    const gatsbyNode = Object.assign({
      // Required Gatsby fields
      id: `airtable${queryName}`,
      parent: "__SOURCE__",
      children: [],
      internal: {
        type: `Airtable-${queryName}`,
        contentDigest: crypto
          .createHash("md5")
          .update(JSON.stringify(rows))
          .digest("hex")
      }
    }, rows);

    createNode(gatsbyNode);
  });
```

**Comment by kevzettler** [comment]
@edbrannin I am sold on your [second point suggestion](https://github.com/kevzettler/gatsby-source-airtable/issues/3#issuecomment-370979565) for a next iteration of this plugin. That would at-least enable GraphQL interface support to the 1 table Airtable restriction.  

I don't have any personal capacity to develop and implement it at the moment but will accept PR's

I like your first point on specifying the table names as part of the config as well. Without a way query a list of table names form Airtable I can't think of a more elegant way.

**Comment by ethanlee16** [comment]
Seems like it's on its way, the Base schema API is listed under Airtable's [beta features request form](https://airtable.com/shrLK2dGvhx46S6bU). I've requested access and would love to try this if I get it/when it is publically available!

**Comment by kevzettler** [comment]
Adding to this discussion. You can configure multiple table support by adding multiple table configuration objects to gatsby-conf.js This will not let you do queries across tables/bases but you can have multiple in the same project

for more information see https://github.com/kevzettler/gatsby-source-airtable/issues/8

**Comment by jbolda** [comment]
This has been added to the `latest` version of the plugin on Gatsby v2.
